{
 "title": "MTP_Meteostanice",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Název zařízení",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"device\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Název SSID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"SSID\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Celkový počet měření",
   "type": "gauge",
   "description": "počet měření se odvíjí od \"time range\" nastaveného vpravo nahoře.",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "x" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(\"teplota\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Aktuální Nadmořská Výška",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m n. m." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"nadmorskaVyska\", \"time\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Aktuální Teplota",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"teplota\", \"time\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Teplota Graf",
   "type": "timeseries",
   "description": "Historie teploty čtená z meteostanice",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"teplota\", \"time\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Nejmenší teplota",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MIN(\"teplota\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Největší teplota",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MAX(\"teplota\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Průměrná teplota",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT AVG(\"teplota\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Aktuální Vlhkost",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"vlhkost\", \"time\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Vlhkost Graf",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"vlhkost\", \"time\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Nejmenší vlhkost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MIN(\"vlhkost\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Největší vlhkost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MAX(\"vlhkost\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Průměrná vlhkost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT AVG(\"vlhkost\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Aktuální Tlak",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"baroTlak\", \"time\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Barometrický tlak Graf",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"baroTlak\", \"time\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Nejmenší tlak",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MIN(\"baroTlak\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Největší tlak",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MAX(\"baroTlak\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Průměrný tlak",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT AVG(\"baroTlak\") FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  }
 ]
}